---
title: "Lag Comparison"
author: "Indigo Edwards"
date: "10/18/2021"
output: html_document
---

Next steps: 
1. (later) compare between-season phenology - frass/cc centroid difference from overall mean relationship across years
1. (later) write up summary report

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set(fig.width = 12, fig.height = 12)

library(ggplot2)

source('scripts/functions.R')

comp_data <- read_csv('data/processed_data/weekly_stats_2015-2021_rel2.csv')
```

## Mean mass of frass at NCBG

```{r ncbg mean mass, echo = F}
map(
  c('meanBiomass', 'fracSurveys', 'meanDensity'),
  function(v){
    map(
      c(2015:2019,2021),
      function(y){
        temp <- 
          comp_data %>% 
          group_by(site, year) %>% 
          mutate(
            '0' = mean_mass,
            '1' = lead(mean_mass, 1),
            '2' = lead(mean_mass, 2),
            '3' = lead(mean_mass, 3),
            '-1' = lag(mean_mass, 1),
            '-2' = lag(mean_mass, 2),
            '-3' = lag(mean_mass, 3)) %>% 
          filter(year == y, site == 'NC Botanical Garden') %>% 
          ungroup()
        
        temp %>% 
          select('0','1','2','3','-1','-2','-3') %>% 
          map(~lm(pull(temp, v) ~ .x, data = temp)) %>% 
          map(summary) %>% 
          map('r.squared') %>% 
          bind_cols() %>% 
          pivot_longer(
            cols = '0':'-3',
            names_to = 'lag',
            values_to = 'R2') %>% 
          mutate(
            site = 'NC Botanical Garden',
            year = y,
            var = v,
            lag = as.double(lag),
            .before = 'R2')
      }) %>% bind_rows()
  }) %>% bind_rows() %>% 
  ggplot(
    aes(
      x = lag,
      y = R2,
      color = var)) +
  geom_point() +
  facet_wrap(~year) +
  scale_color_hue(
    labels = c(
      'Fraction of Surveys',
      'Mean Caterpillar Biomass',
      'Mean Caterpillar Density')) +
  labs(
    x = 'Time Adjustment of Mean Frass Mass Measurements',
    y = 'R^2',
    color = 'CC Variable')
```

## Mean number of frass at NCBG

```{r ncbg mean number, echo = F}
map(
  c('meanBiomass', 'fracSurveys', 'meanDensity'),
  function(v){
    map(
      c(2015:2019,2021),
      function(y){
        temp <- 
          comp_data %>% 
          group_by(site, year) %>% 
          mutate(
            '0' = mean_number,
            '1' = lead(mean_number, 1),
            '2' = lead(mean_number, 2),
            '3' = lead(mean_number, 3),
            '-1' = lag(mean_number, 1),
            '-2' = lag(mean_number, 2),
            '-3' = lag(mean_number, 3)) %>% 
          filter(year == y, site == 'NC Botanical Garden') %>% 
          ungroup()
        
        temp %>% 
          select('0','1','2','3','-1','-2','-3') %>% 
          map(~lm(pull(temp, v) ~ .x, data = temp)) %>% 
          map(summary) %>% 
          map('r.squared') %>% 
          bind_cols() %>% 
          pivot_longer(
            cols = '0':'-3',
            names_to = 'lag',
            values_to = 'R2') %>% 
          mutate(
            site = 'NC Botanical Garden',
            year = y,
            var = v,
            lag = as.double(lag),
            .before = 'R2')
      }) %>% bind_rows()
  }) %>% bind_rows() %>% 
  ggplot(
    aes(
      x = lag,
      y = R2,
      color = var)) +
  geom_point() +
  facet_wrap(~year) +
  scale_color_hue(
    labels = c(
      'Fraction of Surveys',
      'Mean Caterpillar Biomass',
      'Mean Caterpillar Density')) +
  labs(
    x = 'Time Adjustment of Mean Frass Mass Measurements',
    y = 'R^2',
    color = 'CC Variable')
```

## Mean mass of frass at Prairie Ridge

```{r pr mean mass, echo = F}
map(
  c('meanBiomass', 'fracSurveys', 'meanDensity'),
  function(v){
    map(
      c(2015, 2018, 2019, 2021),
      function(y){
        temp <- 
          comp_data %>% 
          group_by(site, year) %>% 
          mutate(
            '0' = mean_mass,
            '1' = lead(mean_mass, 1),
            '2' = lead(mean_mass, 2),
            '3' = lead(mean_mass, 3),
            '-1' = lag(mean_mass, 1),
            '-2' = lag(mean_mass, 2),
            '-3' = lag(mean_mass, 3)) %>% 
          filter(year == y, site == 'Prairie Ridge Ecostation') %>% 
          ungroup()
        
        temp %>% 
          select('0','1','2','3','-1','-2','-3') %>% 
          map(~lm(pull(temp, v) ~ .x, data = temp)) %>% 
          map(summary) %>% 
          map('r.squared') %>% 
          bind_cols() %>% 
          pivot_longer(
            cols = '0':'-3',
            names_to = 'lag',
            values_to = 'R2') %>% 
          mutate(
            site = 'Prairie Ridge Ecostation',
            year = y,
            var = v,
            lag = as.double(lag),
            .before = 'R2')
      }) %>% bind_rows()
  }) %>% bind_rows() %>% 
  ggplot(
    aes(
      x = lag,
      y = R2,
      color = var)) +
  geom_point() +
  facet_wrap(~year) +
  scale_color_hue(
    labels = c(
      'Fraction of Surveys',
      'Mean Caterpillar Biomass',
      'Mean Caterpillar Density')) +
  labs(
    x = 'Time Adjustment of Mean Frass Mass Measurements',
    y = 'R^2',
    color = 'CC Variable')
```

## Mean number of frass at Prairie Ridge

```{r pr mean number, echo = F}
map(
  c('meanBiomass', 'fracSurveys', 'meanDensity'),
  function(v){
    map(
      c(2015, 2018, 2019,2021),
      function(y){
        temp <- 
          comp_data %>% 
          group_by(site, year) %>% 
          mutate(
            '0' = mean_number,
            '1' = lead(mean_number, 1),
            '2' = lead(mean_number, 2),
            '3' = lead(mean_number, 3),
            '-1' = lag(mean_number, 1),
            '-2' = lag(mean_number, 2),
            '-3' = lag(mean_number, 3)) %>% 
          filter(year == y, site == 'Prairie Ridge Ecostation') %>% 
          ungroup()
        
        temp %>% 
          select('0','1','2','3','-1','-2','-3') %>% 
          map(~lm(pull(temp, v) ~ .x, data = temp)) %>% 
          map(summary) %>% 
          map('r.squared') %>% 
          bind_cols() %>% 
          pivot_longer(
            cols = '0':'-3',
            names_to = 'lag',
            values_to = 'R2') %>% 
          mutate(
            site = 'Prairie Ridge Ecostation',
            year = y,
            var = v,
            lag = as.double(lag),
            .before = 'R2')
      }) %>% bind_rows()
  }) %>% bind_rows() %>% 
  ggplot(
    aes(
      x = lag,
      y = R2,
      color = var)) +
  geom_point() +
  facet_wrap(~year) +
  scale_color_hue(
    labels = c(
      'Fraction of Surveys',
      'Mean Caterpillar Biomass',
      'Mean Caterpillar Density')) +
  labs(
    x = 'Time Adjustment of Mean Frass Mass Measurements',
    y = 'R^2',
    color = 'CC Variable')
```


